public enum Gender { MALE, FEMALE, NONE }
public enum Parent { FATHER, MOTHER }
public enum Relation
{
    PATERNAL_UNCLE, MATERNAL_UNCLE, PATERNAL_AUNT, MATERNAL_AUNT,
    SISTER_IN_LAW, BROTHER_IN_LAW, SON, DAUGHTER, SIBLINGS,
    NONE
}

enum Command { ADD_CHILD, GET_RELATIONSHIP, NONE }

